import { Check, Ruler, ScanLine, ShieldCheck, ClipboardCheck } from "lucide-react";
import { CTA, SectionIntro } from "../ui";
const img = n => n;
export const metadata={title:"Calidad y metrología",description:"Inspección dimensional, verificación de geometrías y tolerancias y control dimensional para manufactura de precisión."};
export default function Quality(){return <>
 <section className="visual-page-hero"><img src={img("/images/seleccion-30sep/principales/52.webp")} alt="Detalle de placa mecanizada de precisión" data-motion="off"/><div className="visual-page-overlay"/><div className="container visual-page-content" data-reveal><span className="eyebrow">Calidad · Metrología · Inspección</span><h1>La precisión no termina cuando la pieza sale de <em>la máquina.</em></h1><p>Integramos inspección y control dimensional como parte del proceso para verificar que los componentes cumplan con las características requeridas.</p></div></section>
 <section className="section section-white"><div className="container quality-editorial-grid"><div className="quality-copy" data-reveal><span className="eyebrow">Control dimensional</span><h2>Medir también es parte de <em>fabricar.</em></h2><p className="large-copy">Integramos la inspección dimensional al proceso de manufactura para verificar las características relevantes de cada componente de acuerdo con su aplicación.</p><div className="quality-points"><div><Ruler/><span><strong>Inspección dimensional</strong>Verificación de dimensiones y características definidas para el componente.</span></div><div><ScanLine/><span><strong>Geometría y tolerancias</strong>Control de posiciones, diámetros, planicidad, concentricidad y otras características geométricas de acuerdo con el proyecto.</span></div><div><ClipboardCheck/><span><strong>Metrología 3D</strong>Inspección y digitalización de geometrías mediante sistemas de medición tridimensional cuando la aplicación lo requiere.</span></div></div></div><div className="quality-photo-mosaic"><img className="q-main" src={img("/images/seleccion-30sep/principales/web32.webp")} alt="Placas mecanizadas"/><img className="q-small" src={img("/images/seleccion-30sep/secundarias/web-51.webp")} alt="Detalle de mecanizado"/></div></div></section>
 <section className="full-bleed-photo-section"><img src={img("/images/seleccion-30sep/secundarias/76.webp")} alt="Detalle de componente de precisión" data-motion="off"/><div className="full-bleed-photo-overlay"/><div className="container full-bleed-photo-copy" data-reveal><span className="eyebrow">En cada proyecto</span><h2>Control desde el desarrollo hasta la <em>inspección final.</em></h2><p>Definir, fabricar, inspeccionar y entregar con la misma lógica de precisión.</p></div></section>
 <section className="section section-white"><div className="container quality-photo-grid"><div className="quality-photo-main"><img src={img("/images/seleccion-30sep/secundarias/web40.webp")} alt="Componente en máquina durante el proceso de manufactura"/><div><ShieldCheck size={25}/><span><strong>Precisión en todo el proceso.</strong>La inspección es parte de la solución, no un paso aislado.</span></div></div><div><SectionIntro eyebrow="Capacidad" title="Controlamos los detalles que importan." text="Las capacidades descritas corresponden a los procesos y controles disponibles en Detoch More. La documentación específica de cada proyecto puede definirse según sus requerimientos."/><ul className="check-list"><li><Check size={16}/>Dimensiones críticas</li><li><Check size={16}/>Ajustes y tolerancias</li><li><Check size={16}/>Geometría</li><li><Check size={16}/>Posición y concentricidad</li><li><Check size={16}/>Acabados funcionales</li><li><Check size={16}/>Correspondencia entre componentes</li></ul></div></div></section><CTA compact/>
 </>}
