import { Check, Ruler, ScanLine, ShieldCheck, ClipboardCheck } from "lucide-react";
import { CTA, SectionIntro } from "../ui";
const img=n=>`/images/edited/edit-${String(n).padStart(2,"0")}.webp`;
export const metadata={title:"Calidad y metrología",description:"Inspección dimensional, verificación de geometrías y tolerancias y control dimensional para manufactura de precisión."};
export default function Quality(){return <>
 <section className="visual-page-hero"><img src={img(26)} alt="Detalle de placa mecanizada de precisión" data-motion="off"/><div className="visual-page-overlay"/><div className="container visual-page-content" data-reveal><span className="eyebrow">Calidad · Metrología · Inspección</span><h1>La precisión no termina cuando sale de <em>la máquina.</em></h1><p>Integramos inspección y control dimensional como parte del proceso para verificar que los componentes cumplan con las características requeridas.</p></div></section>
 <section className="section section-white"><div className="container quality-editorial-grid"><div className="quality-copy" data-reveal><span className="eyebrow">Control dimensional</span><h2>Medir también es parte de <em>fabricar.</em></h2><p className="large-copy">Nuestro proceso contempla la inspección de componentes y la verificación de geometrías y tolerancias, antes de la entrega.</p><div className="quality-points"><div><Ruler/><span><strong>Inspección dimensional</strong>Verificación de dimensiones críticas.</span></div><div><ScanLine/><span><strong>Geometrías y tolerancias</strong>Comprobación de características especificadas.</span></div><div><ClipboardCheck/><span><strong>Control durante manufactura</strong>Seguimiento dimensional del proceso.</span></div></div></div><div className="quality-photo-mosaic"><img className="q-main" src={img(28)} alt="Placas mecanizadas"/><img className="q-small" src={img(18)} alt="Detalle de mecanizado"/></div></div></section>
 <section className="full-bleed-photo-section"><img src={img(25)} alt="Detalle de componente de precisión" data-motion="off"/><div className="full-bleed-photo-overlay"/><div className="container full-bleed-photo-copy" data-reveal><span className="eyebrow">En cada proyecto</span><h2>Ingeniería, fabricación e inspección forman un <em>solo flujo.</em></h2><p>Definir, fabricar, inspeccionar y entregar con la misma lógica de precisión.</p></div></section>
 <section className="section section-white"><div className="container quality-photo-grid"><div className="quality-photo-main"><img src={img(1)} alt="Placa perforada de precisión"/><div><ShieldCheck size={25}/><span><strong>Precisión en todo el proceso.</strong>La inspección es parte de la solución, no un paso aislado.</span></div></div><div><SectionIntro eyebrow="Capacidad" title="Controlamos los detalles que importan." text="Las capacidades descritas corresponden a los procesos y controles disponibles en Detoch More. La documentación específica de cada proyecto puede definirse según sus requerimientos."/><ul className="check-list"><li><Check size={16}/>Inspección dimensional</li><li><Check size={16}/>Verificación de geometrías</li><li><Check size={16}/>Verificación de tolerancias</li><li><Check size={16}/>Control dimensional durante manufactura</li><li><Check size={16}/>Ajuste y ensamble de precisión</li></ul></div></div></section><CTA/>
 </>}
