import Link from "next/link";
import { ArrowUpRight, Boxes, DraftingCompass, RefreshCcw, Wrench } from "lucide-react";
import { CTA, SectionIntro } from "../ui";
const img = n => n;
export const metadata={title:"Servicios",description:"Ingeniería y desarrollo, soluciones para la industria farmacéutica, formatos, herramentales y componentes de precisión."};
const services=[
 {icon:DraftingCompass,number:"01",title:"Ingeniería y desarrollo",image: "/images/seleccion-30sep/principales/65.webp",intro:"Convertimos necesidades de proceso en soluciones de ingeniería manufacturables.",items:["Análisis de necesidades y problemáticas en equipos y procesos","Desarrollo de soluciones de ingeniería","Diseño y rediseño de componentes y herramentales","Ingeniería inversa","Modelado 3D y documentación técnica","Optimización y adaptación de componentes"]},
 {icon:Boxes,number:"02",title:"Soluciones para la industria farmacéutica",image: "/images/seleccion-30sep/principales/62.webp",intro:"Desarrollamos y manufacturamos soluciones de ingeniería, formatos, herramentales y componentes de precisión.",items:["Formatos y cambios de formato para maquinaria de producción y empaque","Blisteras: componentes de formato, sellado, arrastre y troquelado","Estuchadoras: guías, empujadores, cangilones y componentes de formato","Llenadoras y taponadoras: estrellas, guías, pinzas y componentes para manejo de producto","Etiquetadoras: componentes y formatos para manejo de frascos","Refacciones y componentes de precisión para maquinaria farmacéutica","Rediseño y mejora de componentes"]},
 {icon:Wrench,number:"03",title:"Componentes y herramentales",image: "/images/seleccion-30sep/principales/web14-portada-2.webp",intro:"Desde un componente de precisión hasta un cambio de formato completo.",items:["Componentes de precisión","Herramentales","Cambios de formato","Refacciones","Diseño para manufactura","Ajuste y ensamble"]},
 {icon:RefreshCcw,number:"04",title:"Optimización y rediseño",image: "/images/seleccion-30sep/secundarias/85.webp",intro:"Mejoramos componentes para resolver problemas de funcionamiento, desgaste o desempeño.",items:["Adaptación de componentes","Rediseño de piezas existentes","Ingeniería inversa","Documentación técnica","Validación dimensional"]}
];
export default function Services(){return <>
 <section className="visual-page-hero"><img src={img("/images/seleccion-30sep/principales/68.webp")} alt="Componentes mecanizados de formato" data-motion="off"/><div className="visual-page-overlay"/><div className="container visual-page-content" data-reveal><span className="eyebrow">Soluciones</span><h1>De la necesidad a la <em>solución.</em></h1><p>Integramos ingeniería y manufactura para desarrollar soluciones funcionales para maquinaria y procesos industriales.</p></div></section>
 <section className="section section-white"><div className="container"><SectionIntro eyebrow="Lo que resolvemos" title="Ingeniería aplicada a necesidades reales de producción."/><div className="service-editorial-list">{services.map(({icon:Icon,...s})=><article className="service-editorial-card" key={s.number}><div className="service-editorial-photo"><img src={img(s.image)} alt={s.title}/><span>{s.number}</span></div><div className="service-editorial-copy"><div className="service-top"><span>{s.number}</span><Icon size={25}/></div><h2>{s.title}</h2><p>{s.intro}</p><ul>{s.items.map(item=><li key={item}>{item}</li>)}</ul></div></article>)}</div></div></section>
 <section className="full-bleed-photo-section"><img src={img("/images/seleccion-30sep/secundarias/70.webp")} alt="Detalle de conjunto de formato" data-motion="off"/><div className="full-bleed-photo-overlay"/><div className="container full-bleed-photo-copy" data-reveal><span className="eyebrow">Ingeniería aplicada</span><h2>Una solución se diseña para <em>funcionar.</em></h2><p>Partimos del problema, desarrollamos la respuesta y la llevamos a manufactura.</p><Link className="button button-light" href="/contacto">Consultar a ingeniería <ArrowUpRight size={18}/></Link></div></section><CTA/>
 </>}
