import { CTA, SectionIntro } from "../ui";
const img = n => n;
export const metadata = { title: "Sobre nosotros", description: "Conoce a Detoch More, empresa mexicana especializada en ingeniería y manufactura de precisión para la industria farmacéutica." };
export default function About(){return <>
  <section className="visual-page-hero"><img src={img("/images/seleccion-30sep/principales/web43.webp")} alt="Componentes y formatos Detoch More" data-motion="off"/><div className="visual-page-overlay"/><div className="container visual-page-content" data-reveal><span className="eyebrow">Sobre Detoch More</span><h1>Ingeniería que entiende el <em>proceso.</em></h1><p>Desarrollamos y fabricamos soluciones de precisión para aplicaciones donde la funcionalidad, la repetibilidad y el detalle importan.</p></div></section>
  <section className="section section-white"><div className="container asymmetric-two-col about-visual-layout"><div className="sticky-copy" data-reveal><span className="eyebrow">Quiénes somos</span><h2>Una empresa mexicana de ingeniería y manufactura de <em>precisión.</em></h2></div><div className="about-copy about-copy-visual"><div className="about-photo-wide"><img src={img("/images/seleccion-30sep/principales/63.webp")} alt="Selección de componentes y formatos"/></div><p className="large-copy">Detoch More es una empresa mexicana especializada en ingeniería y manufactura de precisión, con experiencia en componentes, herramentales y formatos para la industria farmacéutica.</p><p>Nuestro trabajo parte de comprender la función de cada pieza dentro del proceso. A partir de ello desarrollamos, fabricamos e inspeccionamos soluciones orientadas a integrarse correctamente en su aplicación.</p><div className="statement"><strong>No nos limitamos a fabricar componentes.</strong><span>Entendemos su función dentro del proceso.</span></div></div></div></section>
  <section className="about-image-break"><div className="about-image-break-photo"><img src={img("/images/seleccion-30sep/principales/67.webp")} alt="Colección de componentes mecanizados de precisión"/></div><div className="about-image-break-copy" data-reveal><span className="eyebrow">Nuestra dirección</span><h2>Precisión, respuesta y <em>confiabilidad.</em></h2><p>Desarrollar y fabricar soluciones de ingeniería de precisión para la industria farmacéutica, entendiendo las necesidades de cada proyecto.</p></div></section>
  <section className="section section-white"><div className="container"><SectionIntro eyebrow="Forma de trabajo" title="La forma en que hacemos nuestro trabajo."/><div className="values-light values-editorial"><div><span>Entender</span><p>Comprendemos la función del componente y su interacción con el proceso.</p></div><div><span>Desarrollar</span><p>Definimos una solución técnicamente viable y fabricable.</p></div><div><span>Fabricar</span><p>Controlamos el proceso de manufactura de acuerdo con los requerimientos de la aplicación.</p></div><div><span>Verificar</span><p>Inspeccionamos las características críticas antes de entregar.</p></div></div></div></section><CTA compact/>
</>}
