import { CTA, SectionIntro } from "../ui";
const img = n => `/images/edited/edit-${String(n).padStart(2,"0")}.webp`;
export const metadata = { title: "Sobre nosotros", description: "Conoce a Detoch More, empresa mexicana especializada en ingeniería y manufactura de precisión para la industria farmacéutica." };
export default function About(){return <>
  <section className="visual-page-hero"><img src={img(20)} alt="Componentes y formatos Detoch More" data-motion="off"/><div className="visual-page-overlay"/><div className="container visual-page-content" data-reveal><span className="eyebrow">Sobre Detoch More</span><h1>Ingeniería y Manufactura de <em>Precisión</em></h1><p>Ingeniería y manufactura especializada en formatos y componentes para maquinaria farmacéutica.</p></div></section>
  <section className="section section-white"><div className="container asymmetric-two-col about-visual-layout"><div className="sticky-copy" data-reveal><span className="eyebrow">Quiénes somos</span><h2>Una empresa mexicana de ingeniería y manufactura de <em>precisión.</em></h2></div><div className="about-copy about-copy-visual"><div className="about-photo-wide"><img src={img(23)} alt="Selección de componentes y formatos"/></div><p className="large-copy">En Detoch More somos una empresa mexicana especializada en ingeniería y manufactura de precisión para la industria farmacéutica.</p><p>Analizamos la aplicación, las condiciones de operación y la necesidad del cliente para desarrollar una solución funcional, integrando diseño, manufactura e inspección.</p><p>Nos involucramos desde la identificación del problema hasta la implementación de la solución, lo que nos permite responder con rapidez y mantener control sobre cada etapa del proyecto.</p><div className="statement"><strong>No nos limitamos a fabricar componentes.</strong><span>Entendemos su función, desarrollamos la solución y la llevamos a manufactura.</span></div></div></div></section>
  <section className="about-image-break"><div className="about-image-break-photo"><img src={img(5)} alt="Sistema de guiado mecanizado"/></div><div className="about-image-break-copy" data-reveal><span className="eyebrow">Nuestra dirección</span><h2>Precisión, rapidez y <em>confiabilidad.</em></h2><p>Desarrollar y fabricar soluciones de ingeniería de precisión para la industria farmacéutica, entendiendo las necesidades de cada proyecto.</p></div></section>
  <section className="section section-white"><div className="container"><SectionIntro eyebrow="Valores" title="La forma en que hacemos nuestro trabajo."/><div className="values-light values-editorial"><div><span>Pasión</span><p>Nos involucramos en cada proyecto con interés genuino por encontrar y desarrollar la solución.</p></div><div><span>Precisión</span><p>Cuidamos los detalles desde el desarrollo de ingeniería hasta la manufactura e inspección.</p></div><div><span>Compromiso</span><p>Nos hacemos responsables de cada proyecto y lo acompañamos hasta lograr el resultado requerido.</p></div><div><span>Mejora continua</span><p>Buscamos mejores procesos, herramientas y formas de trabajar para evaluar nuestras capacidades.</p></div></div></div></section><CTA/>
</>}
