import { ArrowUpRight, FlaskConical, ShoppingCart, ShieldCheck, Wrench } from "lucide-react";
import Link from "next/link";
import { CTA, SectionIntro } from "../ui";
const img = n => n;
export const metadata={title:"Aplicaciones farmacéuticas",description:"Ingeniería y manufactura de formatos y componentes para maquinaria farmacéutica."};
const audiences=[["01","Ingeniería","Desarrollo de componentes y soluciones compatibles con los requerimientos funcionales del equipo.",FlaskConical,"/images/seleccion-30sep/secundarias/web-57.webp"],["02","Mantenimiento","Fabricación y recuperación de componentes para reemplazo, adecuación o mejora.",Wrench,"/images/seleccion-30sep/secundarias/75.webp"],["03","Compras","Soporte para identificar y fabricar componentes especiales con especificaciones claramente definidas.",ShoppingCart,"/images/seleccion-30sep/secundarias/web33.webp"],["04","Calidad","Control dimensional y documentación de características críticas cuando el proyecto lo requiere.",ShieldCheck,"/images/seleccion-30sep/principales/66.webp"]];
export default function Industries(){return <>
 <section className="visual-page-hero applications-hero"><img src={img("/images/seleccion-30sep/principales/57.webp")} alt="Aplicación farmacéutica" data-motion="off"/><div className="visual-page-overlay"/><div className="container visual-page-content" data-reveal><span className="eyebrow">Aplicaciones</span><h1>Entendemos el proceso detrás de <em>la pieza.</em></h1><p>Desarrollamos y fabricamos componentes para diferentes etapas y funciones de maquinaria farmacéutica.</p></div></section>
 <section className="section section-white"><div className="container application-editorial"><div className="application-copy" data-reveal><span className="eyebrow">Industria farmacéutica</span><h2>Formatos y componentes para producción y <em>empaque farmacéutico.</em></h2><p>Desarrollamos y fabricamos componentes de precisión para aplicaciones de cambio de formato, blíster y empaque, alimentación y manejo de producto, llenado y dosificación, así como marcado y codificación.</p></div><div className="application-photo-stack"><img className="application-photo-main" src={img("/images/seleccion-30sep/principales/59.webp")} alt="Cilindros y componentes mecanizados para maquinaria farmacéutica"/><img className="application-photo-float" src={img("/images/seleccion-30sep/secundarias/web-52.webp")} alt="Guías y componentes de precisión para maquinaria farmacéutica"/></div></div></section>
 <section className="section process-section"><div className="container"><SectionIntro eyebrow="A quién ayudamos" title="Información relevante para cada área."/><div className="audience-editorial-grid">{audiences.map(([n,t,d,Icon,photo])=><article key={n} className="audience-editorial-card"><div className="audience-photo"><img src={img(photo)} alt={t}/><span>{n}</span></div><div><Icon size={25}/><h3>{t}</h3><p>{d}</p></div></article>)}</div></div></section>
 <section className="section section-white"><div className="container two-col"><SectionIntro eyebrow="Más que manufactura" title="Una solución debe funcionar en su contexto." text="Por eso nuestro trabajo parte del problema: entendemos la necesidad, desarrollamos la solución, la llevamos a manufactura y verificamos el resultado."/><div className="image-feature image-feature-editorial"><img src={img("/images/seleccion-30sep/secundarias/80.webp")} alt="Conjunto mecánico desarrollado para una aplicación"/><div><span className="eyebrow">Ingeniería aplicada</span><h3>Diseño y documentación que aterrizan en manufactura.</h3><Link href="/capacidades" className="text-link">Ver capacidades <ArrowUpRight size={16}/></Link></div></div></div></section><CTA/>
 </>}
