import { ArrowUpRight, FlaskConical, ShoppingCart, ShieldCheck, Wrench } from "lucide-react";
import Link from "next/link";
import { CTA, SectionIntro } from "../ui";
const img=n=>`/images/edited/edit-${String(n).padStart(2,"0")}.webp`;
export const metadata={title:"Aplicaciones farmacéuticas",description:"Ingeniería y manufactura de formatos y componentes para maquinaria farmacéutica."};
const audiences=[["01","Ingeniería / Proyectos","Soluciones desarrolladas alrededor de la función, el equipo y las necesidades del proceso.",FlaskConical,3],["02","Mantenimiento","Refacciones, reproducción y rediseño de componentes para mantener equipos operando.",Wrench,9],["03","Compras","Un proveedor que integra ingeniería, manufactura e inspección para proyectos de precisión.",ShoppingCart,20],["04","Calidad","Inspección dimensional, geometrías, tolerancias y control dimensional.",ShieldCheck,28]];
export default function Industries(){return <>
 <section className="visual-page-hero"><img src={img(27)} alt="Aplicación farmacéutica" data-motion="off"/><div className="visual-page-overlay"/><div className="container visual-page-content" data-reveal><span className="eyebrow">Aplicaciones</span><h1>Entendemos el proceso detrás de <em>la pieza.</em></h1><p>Desarrollamos y fabricamos componentes para diferentes etapas y funciones de maquinaria farmacéutica.</p></div></section>
 <section className="section section-white"><div className="container application-editorial"><div className="application-copy" data-reveal><span className="eyebrow">Industria farmacéutica</span><h2>Componentes para producción y <em>empaque.</em></h2><p>Desarrollamos y manufacturamos formatos, herramentales y componentes de precisión para maquinaria de producción y empaque.</p><div className="application-list"><div><strong>Cambios de formato</strong><span>Adaptación de maquinaria a nuevas presentaciones.</span></div><div><strong>Blisteras</strong><span>Componentes de formato, sellado, arrastre y troquelado.</span></div><div><strong>Estuchadoras</strong><span>Guías, empujadores, cangilones y componentes de formato.</span></div><div><strong>Llenadoras y taponadoras</strong><span>Estrellas, guías, pinzas y componentes para manejo de producto.</span></div><div><strong>Etiquetadoras</strong><span>Componentes y formatos para manejo de frascos.</span></div><div><strong>Refacciones y rediseño</strong><span>Componentes de precisión y mejoras funcionales.</span></div></div></div><div className="application-photo-stack"><img className="application-photo-main" src={img(16)} alt="Sistema de guiado y transporte"/><img className="application-photo-float" src={img(10)} alt="Detalle de montaje de precisión"/></div></div></section>
 <section className="section process-section"><div className="container"><SectionIntro eyebrow="A quién ayudamos" title="Información relevante para cada área."/><div className="audience-editorial-grid">{audiences.map(([n,t,d,Icon,photo])=><article key={n} className="audience-editorial-card"><div className="audience-photo"><img src={img(photo)} alt={t}/><span>{n}</span></div><div><Icon size={25}/><h3>{t}</h3><p>{d}</p></div></article>)}</div></div></section>
 <section className="section section-white"><div className="container two-col"><SectionIntro eyebrow="Más que manufactura" title="Una solución debe funcionar en su contexto." text="Por eso nuestro trabajo parte del problema: entendemos la necesidad, desarrollamos la solución, la llevamos a manufactura y verificamos el resultado."/><div className="image-feature image-feature-editorial"><img src={img(29)} alt="Conjunto mecánico desarrollado para una aplicación"/><div><span className="eyebrow">Ingeniería aplicada</span><h3>Diseño y documentación que aterrizan en manufactura.</h3><Link href="/capacidades" className="text-link">Ver capacidades <ArrowUpRight size={16}/></Link></div></div></div></section><CTA/>
 </>}
